### PR TITLE
Dark mode

### LINKED ISSUE #94: dark mode support

### PR DESCRIPTION
**Pull request by yuraxdrumz**
Fixes #94 

This pull request allows dynamic theme support and it is implemented using `styled-components`. The idea behind it is we can use css classes as if they were react components, allowing us to write cleaner and more dynamic code with all the latest css features and avoid the inline css + scss styling.
```typescript
const StyledSwitch = styled(Switch)`
  color: ${props=>props.theme.switch.color} !important;
  background: ${props=>props.theme.switch.background} !important;
  transition: none;
`
```

I kept all the former scss files and antd intact.
The components which couldn't have been converted to `styled-components` were overriden in `App.tsx`'s main `createGlobalStyle` component.
```typescript
const GlobalStyles = createGlobalStyle<{ theme: Theme }>`
  #root {
    overflow: hidden;
  }
```

Styled Component's `ThemeProvider` uses React's `context API` meaning any styled component will automatically get the theme props injected into it.

`App.tsx` looks like this
```typescript
export default function App() {
  const [theme, setTheme] = useState<string>('dark')

  function changeTheme() {
    const d = theme === 'white' ? 'dark' : 'white'
    setTheme(d)
  }

  return (
    <ThemeProvider theme={theme === 'white' ? whiteTheme : darkTheme}>
      <BloomRPC changeTheme={changeTheme} theme={theme} />
      <GlobalStyles theme={theme === 'white' ? whiteTheme : darkTheme} />
    </ThemeProvider>
  )
}
```

I am neither a front end developer nor a designer, but its a starting point. and I am sure people will create a cleaner more refined code + look.

[Here](https://styled-components.com/) is the styled-components website for explanations.
Here are some pics:
dark-final
white-final

### CODE REVIEW

**Comment by fenos** [comment]
This is beautiful!! Will look at it over the weekend!!! Sorry for the late answer

**Comment by fenos** [comment]
@yuraxdrumz Hello!

I've spent a couple of hours this weekend going through this goodie, it looks great but I've found a couple of tiny regressions which I'd like to address before we merge this.

Let's aim to merge this end of the coming week with the current list of things to address:

- Metadata panel is not resizable any longer to the top
- Highlight Interactive switch in dark-mode 
- View proto sidebar looks very weird 😄 
- The bottom border is missing under the word `Editor` - `Response` in Light Mode theme
- The address bar is too long we can make it smaller and increase the size of the gRPC method name (Unary, Server Side Streaming etc...)
- Keep the dark-blue colour in the light mode, exactly like now (top bar where it says "Protos") - (grpc method name) - (Metadata headbar)

I'll be happy to contribute to this too

**Comment by yuraxdrumz** [comment]
Hello @fenos 
I am all for it, I can work on this every evening and I believe we can finish this PR until the end of the week.

**Comment by yuraxdrumz** [comment]
@fenos 
Regarding the issues that are still not addressed, I would love for you to give a more detailed explanation/PR/examples.

**Comment by yuraxdrumz** [comment]
@fenos Any progress? I would love to address the issues we discussed to merge this :)

**Comment by nateshmbhat** [comment]
any updates on this ? This is really needed @fenos

**Comment by jackielii** [comment]
@yuraxdrumz do you mind resolving the conflicts? I'll review and merge

**Review by jackielii — COMMENTED** [review]
@yuraxdrumz Thanks for updating this PR,

A couple of feedbacks:



1. I think we should make the Light theme as default and also we should have a proper Icon for it instead of a tick, same for dark theme
2. Filter button not working, it's a new feature recently added
3. Metadata panel bottom positioning too low when collapsed
4. Play Button not positioned properly
5. the font color for the URL should have more contrast

Overall it's a big change, but I'm not against it and I think @fenos likes it. So if you could resolve the last remaining comments, I'll merge.

**Comment by yuraxdrumz** [comment]
@jackielii thanks for the feedback. As I said, Im a not a frontend developer, that is why I dont see these small UI changes 😁
I will hopefully get to work on the remaining fixes tomorrow.

**Comment by BGCastro89** [comment]
What's the status on this? Is it still on hold? Seems like a great addition!
Assuming it runs on the Linux build, I look forward to using it.

**Comment by paolotakagi** [comment]
wanted to ping this in the hopes it would get merged sometime :)

**Comment by yuraxdrumz** [comment]
Hey guys, I switched to an m1 mac and cant get anything to work. I will try do resolve conflicts over the weekend. Sorry for the delay.

**Comment by dan-autonomic** [comment]
bump!

**Comment by wlacruzpy** [comment]
Is it possible to test it out? is it stable?

**Pull request closed without merging**
