### PR TITLE
Introduce error details

### PR DESCRIPTION
**Pull request by Syperia**
## Feature

Issue Link: https://github.com/uw-labs/bloomrpc/issues/37

### Before

Usually server along with error message and code sends metadata with field validations, error details etc. There was no chance to see them...

### After
Untill now:
image

### Possible improvements
Move proto folder and corresponding protobufjs npm scripts to bloomrpc-mock package

### CODE REVIEW

**Comment by templatevk** [comment]
hyi-pizda

**Comment by fenos** [comment]
This is a great! An amazing addition to the editor! I'm glad you contributed on this!

Overall the technical implementation is good for the purpose you wanted to achieve. I just have few concerns listed below, please help me clarifying this.

- The implementation of displaying the error messages looks very coupled to the `google/rpc` package. In Order to have metadata displayed (as in the screenshot you provided) it needs to be respect that contract. That might be an issue for a very generic editor that should work for any kind of grpc request without caring what's in your backend.  I agree that `google/rpc` is a very common way of representing errors, but, is there a way we can display the same output being more generic? This would also remove the needs of including those proto-files within the codebase.

- I also think that 90% of the time metadata is returned as part of a bad request. But it could also possible to provide metadata on a successful request. If we support the display of metadata i think it should also be generic enough to be compatible with a successful or bad request. What do you think?

-

**Comment by Syperia** [comment]
@fenos 
Speaking of the first question, more generic variant is quite challenging, I have to make an investigation. However current implementation will at least cover those who use `google/rpc` error details. I also don't like having proto-files within the codebase.

About metadata on a successful request. Unfortunately if we take a look at grpc-node Client, we see that it simply ignores metadata if `status.code === Status.OK`:
```typescript
  private handleUnaryResponse<ResponseType>(
      call: Call, deserialize: (value: Buffer) => ResponseType,
      callback: UnaryCallback<ResponseType>): void {
    let responseMessage: ResponseType|null = null;
    call.on('data', (data: Buffer) => {
      if (responseMessage != null) {
        call.cancelWithStatus(Status.INTERNAL, 'Too many responses received');
      }
      try {
        responseMessage = deserialize(data);
      } catch (e) {
        call.cancelWithStatus(
            Status.INTERNAL, 'Failed to parse server response');
      }
    });
    call.on('end', () => {
      if (responseMessage == null) {
        call.cancelWithStatus(Status.INTERNAL, 'Not enough responses received');
      }
    });
    call.on('status', (status: StatusObject) => {
      /* We assume that call emits status after it emits end, and that it
       * accounts for any cancelWithStatus calls up until it emits status.
       * Therefore, considering the above event handlers, status.code should be
       * OK if and only if we have a non-null responseMessage */
      if (status.code === Status.OK) {
        callback(null, responseMessage as ResponseType);
      } else {
        const error: ServiceError =
            Object.assign(new Error(status.details), status);
        callback(error);
      }
    });
  }
```

**Comment by Syperia** [comment]
@fenos I tweaked PR. Now it can parse custom errors as well.
image
All bloom-rpc user have to do, is add the import path with proto file that describe error format.

**Comment by fenos** [comment]
@Syperia Sorry for the delay on reviewing this but i'm about to move house so i'm a bit busy on packing and preparing staff 😄 I'll be back fully in 1-2 weeks time, will also release lots of new features on bloomrpc.

I gave a quick look to the latest commit and it looks already much better, but i'll dig into it soon. 
Thanks again for this goody

**Comment by fenos** [comment]
I haven't forgot about this, i will get back to this soon/

Apologise for the delay

**Comment by oneslash** [comment]
guys, this would be very helpful cc: @fenos

**Comment by QuentinBrosse** [comment]
Do you need help :) @fenos

**Comment by spoonscen** [comment]
Can we pick this up again? I would be happy to if someone needs to take this over.

**Comment by Webonaute** [comment]
any update on this?

**Comment by DannyFeliz** [comment]
I would love to have this merged

**Comment by Webonaute** [comment]
4  month later,  anything?

**Comment by optiman** [comment]
If anyone is interested, I made a fork, updated it and made a release for Linux.
https://github.com/optiman/bloomrpc/releases/tag/1.4.1-errordetails

**Review by lennycampino — APPROVED** [review]
LGTM

**Comment by Webonaute** [comment]
@optiman is it possible to have a build for Mac?

**Comment by optiman** [comment]
@Webonaute you need to have a Mac to build for Mac, which I don't have.
On Linux DMG build fails:
```
Error: spawn hdiutil ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:269:19)
    at onErrorNT (internal/child_process.js:465:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
```
But before it failed, a `BloomRPC-1.4.1-mac.zip` file was generated. I attached it to release. Hope it helps.
You can try to build it by yourself, just clone my repo and run `yarn build && electron-builder build -m` (-m for Mac).

**Comment by jackielii** [comment]
@Syperia I have recently started to maintain this repo. Do you mind resolve the conflicts, I think this is a reasonable PR, will get it merged.

**Comment by hangingman** [comment]
@Syperia Would you please resolve git conflict ? I would like to use this feature.

**Comment by maja42** [comment]
Any updates on this?

**Comment by DannyFeliz** [comment]
Just use postman, it's much better than this:

1. Click New
2. Select gRPC request
3. ...
4. Profit!

https://user-images.githubusercontent.com/5460365/147570317-d7c51c16-e053-44dc-94c2-9c5831953ef2.mp4

**Pull request closed without merging**
